//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team6JQDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPOINTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPOINTMENT()
        {
            this.SCHEDULED_SERVICE = new HashSet<SCHEDULED_SERVICE>();
        }
    
        public int Appointment_ID { get; set; }
        public Nullable<int> Dentist_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<System.DateTime> Appointment_Date { get; set; }
        public Nullable<System.DateTime> Appointment_Time { get; set; }
    
        public virtual DENTIST DENTIST { get; set; }
        public virtual PATIENT PATIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEDULED_SERVICE> SCHEDULED_SERVICE { get; set; }
    }
}
