//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team6JQDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPLETED_SERVICE
    {
        public int Completed_Service_ID { get; set; }
        public Nullable<int> Service_ID { get; set; }
        public Nullable<int> Visit_ID { get; set; }
    
        public virtual SERVICE SERVICE { get; set; }
        public virtual VISIT VISIT { get; set; }
    }
}
