//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team6JQDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENT()
        {
            this.APPOINTMENTs = new HashSet<APPOINTMENT>();
            this.VISITs = new HashSet<VISIT>();
        }
    
        public int Patient_ID { get; set; }
        public Nullable<int> Account_ID { get; set; }
        public string Patient_First_Name { get; set; }
        public string Patient_Middle_Name { get; set; }
        public string Patient_Last_Name { get; set; }
        public string Patient_Street { get; set; }
        public string Patient_City { get; set; }
        public string Patient_State { get; set; }
        public string Patient_Zip { get; set; }
        public string Patient_Phone_Primary { get; set; }
        public string Patient_Phone_Secondary { get; set; }
        public string Patient_SSN { get; set; }
        public Nullable<System.DateTime> Patient_DOB { get; set; }
        public Nullable<bool> Patient_Minor { get; set; }
        public string Patient_Head_Of_House { get; set; }
        public string Patient_Allergies { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISIT> VISITs { get; set; }
    }
}
