//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team6JQDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VISIT()
        {
            this.COMPLETED_SERVICE = new HashSet<COMPLETED_SERVICE>();
        }
    
        public int Visit_ID { get; set; }
        public Nullable<int> Dentist_ID { get; set; }
        public Nullable<int> Patient_ID { get; set; }
        public Nullable<System.DateTime> Visit_Date { get; set; }
        public Nullable<System.DateTime> Visit_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPLETED_SERVICE> COMPLETED_SERVICE { get; set; }
        public virtual DENTIST DENTIST { get; set; }
        public virtual PATIENT PATIENT { get; set; }
    }
}
